name: FE deploy CI on Pull Request

on:
  pull_request:
    branches: [ "deploy" ]

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: 의존성을 설치한다
        run: npm install

      - name: 테스트를 수행한다
        run: npm run test
